#!/bin/bash

# shows usage instructions
usage()
{
cat << EOF
usage: $0 [options]

This script installs the Solarized styles for gedit 3 or pluma (MATE)

OPTIONS:
  -h    Shows this message
  
gedit3 (GNOME):
  -a    Install for all users
  -l    Install only for you

pluma (MATE):
  -A    Install for all users
  -L    Install only for you
EOF
}

chkdir()
{
if [ ! -d "$INSTALLPATH" ]; then
    if [ "$NEEDSUDO" == true ]; then
        sudo mkdir -p "$INSTALLPATH"
    else
        mkdir -p "$INSTALLPATH"
    fi
fi
}

# path to install to
INSTALLPATH=$HOME/.local/share/gedit/styles
# will need to use sudo to install for all users
NEEDSUDO=false

# loop through passed arguments
while getopts "halAL" OPTION
do
    case $OPTION in
        h)
            usage
            exit 1
            ;;
        a)
            INSTALLPATH=/usr/share/gtksourceview-3.0/styles
            NEEDSUDO=true
            ;;
        A)
            INSTALLPATH=/usr/share/gtksourceview-2.0/styles
            NEEDSUDO=true
            ;;
        l)
            INSTALLPATH=$HOME/.local/share/gedit/styles
            ;;
        L)
            INSTALLPATH=$HOME/.config/pluma/styles
            ;;
        ?)
            INSTALLPATH=$HOME/.local/share/gedit/styles
            ;;
    esac # is ridiculous
done

# install for all users when sudo set to true
if [ "$NEEDSUDO" == true ]; then
    chkdir
    sudo cp solarized-*.xml "$INSTALLPATH"
else
    chkdir
    cp solarized-*.xml "$INSTALLPATH"
fi
